export default firstIndicatorStyles = {
        stepIndicatorSize: 40,
        currentStepIndicatorSize: 45,
        separatorStrokeWidth: 3,
        currentStepStrokeWidth: 5,
        separatorFinishedColor: "#4aae4f",
        separatorUnFinishedColor: "#a4d4a5",
        stepIndicatorFinishedColor: "#4aae4f",
        stepIndicatorUnFinishedColor: "#a4d4a5",
        stepIndicatorCurrentColor: "#ffffff",
        stepIndicatorLabelFontSize: 20,
        currentStepIndicatorLabelFontSize: 20,
        stepIndicatorLabelCurrentColor: "#000000",
        stepIndicatorLabelFinishedColor: "#ffffff",
        stepIndicatorLabelUnFinishedColor: "rgba(255,255,255,0.5)",
        labelColor: "#666666",
        labelSize: 20,
        currentStepLabelColor: "#4aae4f",
       
      };